# Generated by Django 5.0.6 on 2024-05-15 20:44

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Debt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("government_id", models.CharField(max_length=50)),
                ("email", models.CharField(max_length=200)),
                ("debt_amount", models.FloatField()),
                ("debt_due_date", models.DateField()),
                ("debt_id", models.CharField(max_length=300)),
            ],
            options={
                "db_table": "debt",
            },
        ),
    ]
